### ISSUE TITLE
When I change some pluggin settings, settings set though "Configure outputs" are immediately reset

### ISSUE THREAD

**Issue by tmarkov** [WayfireWM/wcm#29]
In particular, I use DPI scale of 2.0. Yet when I change some unrelated settings, like a keyboard shortcut of some plugin, my DPI settings are reset to 1.0 automatically.

**Comment by soreau** [comment]
This is because wayfire reads settings from the config file, which it does when it reloading any setting, and wdisplays doesn't update wayfire.ini..

What should happen is that wayfire should read the output settings from config only if it can't get them from kanshi, and never read the output settings from wayfire.ini after the initial read. The problem is that [the output management protocol](https://github.com/emersion/kanshi/blob/master/protocol/wlr-output-management-unstable-v1.xml) is lacking features that are already implemented in wayfire with use of the config file for configuring outputs, like mirroring.

**Comment by ammen99** [comment]
> What should happen is that wayfire should read the output settings from config only if it can't get them from kanshi, and never read the output settings from wayfire.ini after the initial read.

Wayfire recently got an option to allow exactly this: https://github.com/WayfireWM/wayfire/blob/master/metadata/workarounds.xml#L34

```
[workarounds]
use_external_output_configuration = true
```

With this, once you configure an output with an external tool (wdisplays, kanshi, whatever), Wayfire will never again look into the config file for that particular output, at least until it is unplugged.
