### ISSUE TITLE
detect keybinding when key is pressed.

### ISSUE THREAD

**Issue by librewish** [WayfireWM/wcm#7]

**Comment by librewish** [comment]
when i want to set 
new keybinding i don't know what its called.
for eg.
i want to set take screenshot when print us pressed but how is the key defined in wayfire?

**Comment by ammen99** [comment]
@librewish The key names are defined in the `<linux/input-event-codes.h>` header, you can find a list of all keys there.

I do agree this is a meaningful addition though, we should be able to implement this.

**Comment by librewish** [comment]
also in wcm
in binding section add drop down for
keyboard binding
touchscreen binding
touchpad binding(when its ready)

**Comment by soreau** [comment]
I have implemented key and button binding grabs dependent on wayfire #328 however I do not have the hardware for touchscreen and touchpad so I cannot implement support for these.

**Comment by ammen99** [comment]
@soreau It is impossible to get touchscreen gestures because these are not part of the Wayland protocol at all. It would be best if you could just present the user with the option to "build" the gesture, it has 3 attributes:

1. Type - "pinch", "swipe" or "edge-swipe"
2. Finger count - 3 or more
3. Direction - Can be left/right/up/down or a combination like `left-up` for swipes, and in/out for pinch
